PaginaSemestral/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:  
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    index, contactanos, nosotros,
    agregar_PC, Listar_PC, modificar_PC, 
    eliminar_pc, registro, agregar_software, listar_software, 
    agregar_al_carrito, ver_carrito, modificar_software, eliminar_software, eliminar_producto, finalizar_compra, productos_view,  limpiar_carrito, agregar_al_carrito
)

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='index'),
    path('nosotros/', nosotros, name='nosotros'),
    path('contactanos/', contactanos, name='contactanos'),
    path('agregar-PC/', agregar_PC, name='agregar_PC'),
    path('listar-pc/', Listar_PC, name='listar_pc'),
    path('modificar-pc/<int:id>/', modificar_PC, name='modificar_pc'),
    path('eliminar-pc/<int:id>/', eliminar_pc, name='eliminar_pc'),
    path('registro/', registro, name='registro'),
    path('agregar_software/', agregar_software, name='agregar_software'),
    path('listar-software/', listar_software, name='listar_software'),
    path('agregar-al-carrito/<str:producto_tipo>/<int:producto_id>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('ver-carrito/', ver_carrito, name='ver_carrito'),
    path('modificar-software/<int:id>/', modificar_software, name='modificar_software'),
    path('eliminar-software/<int:id>/', eliminar_software, name='eliminar_software'), 
    path('eliminar-producto/<int:item_id>/', eliminar_producto, name='eliminar_producto'),
    path('finalizar_compra/', finalizar_compra, name='finalizar_compra'),  
    path('productos/', productos_view, name='productos'),
    path('agregar-al-carrito/<str:producto_tipo>/<int:producto_id>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('limpiar-carrito/', limpiar_carrito, name='limpiar_carrito'),
 
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to='productos', null=True)

    def __str__(self):
        return self.nombre

class PC(models.Model):
    nombre = models.CharField(max_length=100)
    procesador = models.CharField(max_length=100)
    tarjeta_grafica = models.CharField(max_length=100)
    placa_base = models.CharField(max_length=100)
    ram = models.CharField(max_length=100)
    almacenamiento = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to="PC", null=True)
    visible_al_usuario = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
class Software(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to="software", null=True)
    visible_al_usuario = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
    
opciones_consultas = [
    (0, "consulta"),
    (1, "reclamo"),
    (2, "sugerencia"),
    (3, "felicitaciones")
]

class Contactanos(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    fecha_envio = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

class Carrito(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    creado_en = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = 0
        for item in self.items.all():
            total += item.get_precio_total()
        return total
class ItemCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name='items')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, default=1)  # Reemplaza '1' con el ID correcto de ContentType
    object_id = models.PositiveIntegerField(default=1)
    producto = GenericForeignKey('content_type', 'object_id')
    cantidad = models.PositiveIntegerField(default=1)
    agregado_en = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.producto} - {self.cantidad}'

    class Meta:
        verbose_name = 'Item de Carrito'
        verbose_name_plural = 'Items de Carrito'

class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=timezone.now)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Pedido {self.id} de {self.usuario}'


    
class Orden(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Orden {self.id} - Usuario: {self.usuario.username} - Total: {self.total}'

class ItemOrden(models.Model):
    orden = models.ForeignKey(Orden, related_name='items', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    producto = GenericForeignKey('content_type', 'object_id')
    cantidad = models.PositiveIntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.producto} - Cantidad: {self.cantidad} - Precio: {self.precio}'

app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}PC MarketPlace{% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="{% url 'index' %}">
                <img src="{% static 'app/img/goofyCat_upscaled.png' %}" alt="Logo" style="height: 40px; width: auto; margin-right: 10px;">
                <span>PC MarketPlace</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Inicio</a>
                    </li>
                    
                        </a>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'productos' %}">Productos</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'nosotros' %}">Nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contactanos' %}">Contactanos</a>
                    </li>
                    {% if perms.app.view_pc or perms.app.add_pc %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="crudDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Gestión
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="crudDropdown">
                            {% if perms.app.view_pc %}
                            <li><a class="dropdown-item" href="{% url 'listar_pc' %}">Listado PC</a></li>
                            {% endif %}
                            {% if perms.app.add_pc %}
                            <li><a class="dropdown-item" href="{% url 'agregar_PC' %}">Agregar PC</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'agregar_software' %}">Agregar software</a></li>
                            <li><a class="dropdown-item" href="{% url 'listar_software' %}">Listar software</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link nav-link" style="padding: 0; border: none; background: none;">Cerrar sesión</button>
                        </form>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">@{{ user.username }}</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registro' %}">Registrate</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ver_carrito' %}">
                            <i class="fas fa-shopping-cart" style="color: white;"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="footer bg-dark text-white text-center mt-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Enlaces</h4>
                    <ul class="list-inline">
                        <li class="list-inline-item"><a href="{% url 'index' %}" class="text-muted">Inicio</a></li>
                        <li class="list-inline-item"><a href="{% url 'nosotros' %}" class="text-muted">Nosotros</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Redes Sociales</h4>
                    <ul class="list-inline">
                        <li class="list-inline-item"><a href="#" class="text-muted"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a href="#" class="text-muted"><i class="fab fa-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="#" class="text-muted"><i class="fab fa-instagram"></i></a></li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">Contacto</h4>
                    <p class="lead mb-0">
                        Dirección: DuocUC Sede Maipú, Maipú, Chile<br>
                        Teléfono: (56) 978310482<br>
                        Email: emm.cordero@duocuc.cl
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


</body>
</html>

app/templates/app/contactanos.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Contactanos{% endblock %}

{% block content %}
<div class="container">
    <h2>Contactanos!</h2>
    <form action="" class="formulario_contacto" method="post">

        <h2>Contactanos!</h2>
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="btn btn-primary">Enviar</button>
        <button type="reset" class="btn btn-secondary">Limpiar</button>
    </form>
    {% if mensaje %}
        <p class="alert alert-success">{{ mensaje }}</p>
    {% endif %}
</div>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="{% static 'mi_app/scripts/carrito.js' %}"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/style.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

{% endblock %}

{% block title %}Inicio{% endblock %}

{% block content %}
<section id="carouselSection">
    <div class="container-fluid p-0"> <!-- Asegura que el carrusel ocupe todo el ancho -->
        <div id="carouselExample" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner"> <!-- La sección principal del carrusel -->
                <div class="carousel-item active">
                    <img src="{% static 'app/img/fondo.PNG' %}" class="d-block w-100" alt="Software" style="object-fit: contain; height: 450px;">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'app/img/fondo2.PNG' %}" class="d-block w-100" alt="PC" style="object-fit: contain; height: 450px;">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'app/img/fondo3.PNG' %}" class="d-block w-100" alt="Gaming PC" style="object-fit: contain; height: 350px;">
                </div>
            </div>

            <!-- Controles para navegar por el carrusel -->
            <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Anterior</span>
            </a>
            <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Siguiente</span>
            </a>
        </div>
    </div>
</section>

<section id="productosPC">
    <div class="container mt-4">
        <div class="mb-4 text-center">
            <h2>PC de Escritorio</h2>
            <div class="row">
                {% for pc in pcs %}
                <div class="col-md-4 d-flex align-items-center justify-content-center">
                    <div class="card text-center" style="width: 18rem;">
                        <img src="{{ pc.imagen.url }}" class="card-img-top" alt="{{ pc.nombre }}" style="height: 200px; object-fit: contain;">
                        <div class="card-body">
                            <h5 class="card-title">{{ pc.nombre }}</h5>
                            <ul class="list-unstyled">
                                <li><strong>Procesador:</strong> {{ pc.procesador }}</li>
                                <li><strong>Tarjeta Gráfica:</strong> {{ pc.tarjeta_grafica }}</li>
                                <li><strong>Placa Base:</strong> {{ pc.placa_base }}</li>
                                <li><strong>RAM:</strong> {{ pc.ram }}</li>
                                <li><strong>Almacenamiento:</strong> {{ pc.almacenamiento }}</li>
                            </ul>
                            <p class="card-text">{{ pc.descripcion }}</p>
                            <h3>${{ pc.precio }}</h3>
                            <a href="{% url 'agregar_al_carrito' 'pc' pc.id %}" class="btn btn-primary">Agregar al Carrito</a>

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<section id="productosSoftware">
    <div class="container mt-4">
        <div class="mb-4 text-center">
            <h2>Software</h2>
        </div>
        <div class="row">
            {% for software in software %}
            <div class="col-md-4 d-flex align-items-center justify-content-center">
                <div class="card text-center" style="width: 18rem;">
                    <img src="{{ software.imagen.url }}" class="card-img-top" alt="{{ software.nombre }}" style="height: 200px; object-fit: contain;">
                    <div class="card-body">
                        <h5 class="card-title">{{ software.nombre }}</h5>
                        <p class="card-text">{{ software.descripcion }}</p>
                        <h3>${{ software.precio }}</h3>
                        <a href="{% url 'agregar_al_carrito' 'software' software.id %}" class="btn btn-primary">Agregar al Carrito</a>

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>


        <!-- Agrega más tarjetas de productos de software en un futuro-->
    </div>
</div>
</section>
{% endblock %}

app/templates/app/nosotros.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Nosotros{% endblock %}

{% block content %}
<div class="container mt-5"> <!-- Espaciado superior para separar del contenido anterior -->
    <h1 class="map-heading">Encuéntranos Aquí</h1> <!-- Texto de ubicación -->
      
       <iframe
      class="mapa"
      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3326.62012242495!2d-70.75506712430658!3d-33.51125927336541!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662dcd1fe0c7bab%3A0x4d17b82a7ba77488!2sDuoc%20UC%3A%20sede%20Maipu!5e0!3m2!1ses-419!2scl!4v1713664021771!5m2!1ses-419!2scl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"
      width="600"
      height="450"
      style="border:0;"
      allowfullscreen
      loading="lazy"
    ></iframe>
  </div>

{% endblock %}

app/templates/app/productos.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Productos{% endblock %}

{% block css %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'app/css/style.css' %}">
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="mb-4 text-center">
        <h2>Productos</h2>
    </div>

    <div class="row">
        <!-- Productos PC -->
        {% for producto in productos_pc %}
        <div class="col-md-4 d-flex justify-content-center align-items-center mb-4">
            <div class="card text-center">
                <img src="{{ producto.imagen.url }}" class="card-img-top" alt="{{ producto.nombre }}" style="height: 200px; object-fit: contain;">
                <div class="card-body">
                    <h5 class="card-title">{{ producto.nombre }}</h5>
                    <ul class="list-unstyled">
                        <li><strong>Procesador:</strong> {{ producto.procesador }}</li>
                        <li><strong>Tarjeta Gráfica:</strong> {{ producto.tarjeta_grafica }}</li>
                        <li><strong>Placa Base:</strong> {{ producto.placa_base }}</li>
                        <li><strong>RAM:</strong> {{ producto.ram }}</li>
                        <li><strong>Almacenamiento:</strong> {{ producto.almacenamiento }}</li>
                    </ul>
                    <p class="card-text">{{ producto.descripcion }}</p>
                    <p class="card-text">Precio: ${{ producto.precio }}</p>
                    <form method="POST" action="{% url 'agregar_al_carrito' producto_tipo='pc' producto_id=producto.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            Agregar al carrito
                        </button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}

        <!-- Productos Software -->
        {% for producto in productos_software %}
        <div class="col-md-4 d-flex justify-content-center align-items-center mb-4">
            <div class="card text-center">
                <img src="{{ producto.imagen.url }}" class="card-img-top" alt="{{ producto.nombre }}" style="height: 200px; object-fit: contain;">
                <div class="card-body">
                    <h5 class="card-title">{{ producto.nombre }}</h5>
                    <p class="card-text">{{ producto.descripcion }}</p>
                    <p class="card-text">Precio: ${{ producto.precio }}</p>
                    <form method="POST" action="{% url 'agregar_al_carrito' producto_tipo='software' producto_id=producto.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            Agregar al carrito
                        </button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}